### ISSUE TITLE
static code analysis

### ISSUE THREAD

**Issue by kforner** [r-lib/pkgapi#18]
Hello guys,

In Quartz Bio we have one package that contains some static analysis code that seems quite close of what you're doing. The goal was to analyze functions and their dependencies to be able to see if one change in a set of inter-related packages would modify the function behavior. 

I kind of remember that I started using getParseData() source references, but at one point I switched to direct traversal of the code using is.symbol(),  etc. I think it was for performance reasons. 
So the process is:

 - extract the symbols (and their scope operator if any) from the code
 - obtain the definitions/values
 - keep only functions and methods
 - categorize functions in normal and generics
 - obtain all methods for generics...

The code seems to work, I mean we all use it on a daily basis, but it is not bundled in its own package. 

So my point is: do you see an opportunity of collaboration ? 
My interest, besides contributing to open source, would be to have a reliable package maintained by the community. 

Karl.

**Comment by gaborcsardi** [comment]
Hi Karl, I don't mind collaboration, of course. (This repo is already a merge of two projects, by Kirill and me.) But given that you use a different method to extract the data, I am afraid that it would be difficult to merge the two projects.

**Comment by kforner** [comment]
Ok. So maybe the first step would be for me to try using pkgapi for my purpose, and to see if there are missing features.
And maybe expand your test suite ;)

**Comment by gaborcsardi** [comment]
That would be great! If something is missing for you, and it fits the goals of this package, we can add it, of course.

**Comment by gaborcsardi** [comment]
Btw. the reason we are using the parse data is that we need the row and columns positions of the functions.
