### ISSUE TITLE
Who's calling dplyr::groups()?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgapi#5]
What's the best way to find out which of our reverse dependencies call this particular generic, with the help of this package?

**Comment by gaborcsardi** [comment]
You need to map all reverse dependencies.

**Comment by krlmlr** [comment]
Which means

- I need to clone all of them
- I need to install their dependencies
- I call `map_package()` for all cloned paths

?

Is it worthwhile to streamline this a bit, perhaps with some improvements to remotes?

**Comment by gaborcsardi** [comment]
It seems that it would be easy to avoid loading the package, and then you don't need to install the dependencies, or the package itself. I think.

And if this is true, then maybe a `map_cran_package()` function would make sense.

**Comment by krlmlr** [comment]
Cool. Let's rethink this when we have mapping without loading. Do you plan to work in this direction in the near future?

**Comment by gaborcsardi** [comment]
Actually, I am not sure any more. With `exportPattern`, `Depends`, and `import`, it is hard to do this without loading....

Anyway, the plan is to create a database of these, with an API that can answer these questions easily.

**Comment by krlmlr** [comment]
In this current context, the question "who's overriding groups()" may be even more important. I guess your API database will be able to answer that, too. Looking forward to it.
